#!/bin/bash
_NC='\033[0m' 
_G='\033[0;32m' 
_R='\033[0;31m' 

hcpu_ip_list=(`echo $HERONS_CPUS | tr ',' ' '`)
hcpu_name_list=(`echo $HERONS_CPUS_N | tr ',' ' '`)
len=${#hcpu_ip_list[@]}
for (( idx=0; idx<$len; idx++ ));
do
    cpu_ip="${hcpu_ip_list[idx]}"
    cpu_name="${hcpu_name_list[idx]}"
    if nc -z -G 1 $cpu_ip 22 &>/dev/null; then
        printf "${cpu_name} ${_G}ONLINE${_NC}\n"
    else
        printf "${cpu_name} ${_R}OFFLINE${_NC}\n"
    fi
done 
